### ISSUE TITLE
Visual bug with Farmlands and Dirt paths

### ISSUE THREAD

**Issue by Madis0** [UltimatChamp/BetterGrassify#1]
**Is your feature request related to a problem? Please describe.**
Snowy grass, farmland and dirt path are not connected

**Describe the solution you'd like**
I suggest adding support for those blocks as well.

**Describe alternatives you've considered**
I tried adding them manually to advanced settings, farmland looked decent (for default resource pack), dirt path had a visible stripe and snowy grass is a form of grass block so I was unsure how to add that at all.

**Additional context**
![2024-06-01_17 23 37](https://github.com/UltimatChamp/FabricBetterGrass/assets/8611110/4e6c5105-505f-445e-9585-64186048c75d)

**Comment by UltimatChamp** [comment]
_I'll do that for **farmland** only then._

- Dirt paths are not exactly a full-block, hence, the block behind can be seen.
- The way the mod works, connected snowy grass is not possible, _as it is_. _(i will take a peek at that later)_

**Comment by UltimatChamp** [comment]
I've added options for Farmlands and Dirt paths as booleans in 1.0.5, disabled by default, and a tooltip related to that has been added.

**Comment by TheFurryDevil** [comment]
I hope the dirt path and farmland issue can be addressed in the future. At some point I used a mod that did it perfectly, it might have been the original Better Foliage, or Optifine, not sure.

**Comment by UltimatChamp** [comment]
Fast and Fancy Snowy grass has been properly implemented in 1.0.10!

**Comment by notrohit1702** [comment]
> Dirt paths are not exactly a full-block, hence, the block behind can be seen.
> Hydrated farmland has the same problem as the dirt path.

Is it possible to do something like connected textures where if the block above is a path /farmland block, a dirt block automatically makes its top pixels the same texture? I don't really know a lot about how mods work so please excuse me if this is stupid

**Comment by UltimatChamp** [comment]
No.

**Comment by Madis0** [comment]
The full side of the block could be possible though, whether it is worth the effort is a different question.
