### ISSUE TITLE
Crash if install with RyomicLights on 1.20.6

### ISSUE THREAD

**Issue by Noxtor7171** [UltimatChamp/BetterGrassify#26]
### Describe your issue

If install latest BetterGrassify with RyomicLights in 1.20.6 then minecraft is crashing. 

### Mod version

1.1.1+fabric.1.20.1

### Launcher

Prism Launcher

### Additional context

Btw, this issues I had after install 1.0.18+1.20.1 (1.0.17+1.20.1 correct works).

**Comment by UltimatChamp** [comment]
Can provide logs?

**Comment by Noxtor7171** [comment]
[log](https://mclo.gs/fSwitVN)

**Comment by UltimatChamp** [comment]
Thanks for letting me know! I'll publish a new version soon.
