### ISSUE TITLE
1.2.0 Neoforge wrong version

### ISSUE THREAD

**Issue by Skypony94** [UltimatChamp/BetterGrassify#29]
### Describe your issue

Loading Minecraft with BetterGrassify-1.2.0+neo.1.21.1 disppays a message saying it requires the Fabric API upon booting minecraft

### Mod version

BetterGrassify-1.2.0+neo.1.21.1

### Launcher

neoforge

**Comment by UltimatChamp** [comment]
The message is not wrong. You need [**Forgified Fabric API**](https://modrinth.com/mod/forgified-fabric-api) to run the mod on **NeoForge**.
