### ISSUE TITLE
Add a `bettergrassify:connectable/grass` and other similar block tags

### ISSUE THREAD

**Issue by diefesson** [UltimatChamp/BetterGrassify#36]
### Request Description

This could be used as an alternative to the manual block listing in config. Allowing modded blocks to indicate if they should be connectable with BetterGrassify as well as allowing mods like Distant Horizons to know which blocks it should connect in it's LODs just be checking for the parent `bettergrassify:connectable` tag

**Comment by diefesson** [comment]
Related issue link: https://gitlab.com/distant-horizons-team/distant-horizons/-/issues/857

**Comment by diefesson** [comment]
Another advantages of the tag approach is that it's easily editable with datapacks and tools like KubeJS. Allowing for both mod and modpack devs to tweak it's presence

**Comment by UltimatChamp** [comment]
I don't think tags would be suitable. Anyway, 0698176 should've made it easier for mods to add blocks (via mixins) and get blocks.
