### ISSUE TITLE
Better snow applies to doors (both top and bottom parts)

### ISSUE THREAD

**Issue by BlueJayofEvil** [UltimatChamp/BetterGrassify#37]
### Describe your issue

The better snow function applies itself to doors. Both the top and bottom portions are affected. I tried with both OptiFine-like and LambdaBetterGrass-like modes. This can be commonly seen in the snowy igloo-like houses that generate in snowy plains villages due to the doorways being surrounded by snow blocks.
Adding **doors** to the excluded tags fixes this, so a possible solution could be to add that to the default excluded tags to prevent this issue.

### Mod version

1.3.0+fabric.1.21.1

### Launcher

Prism Launcher

### Additional context

Examples:
![2024-11-08_22 30 22](https://github.com/user-attachments/assets/5d4a1274-7628-4366-aca5-60c5ac668cad)
![2024-11-08_22 30 23](https://github.com/user-attachments/assets/8925d636-cf56-4da0-8abb-d788cc28d1c9)
![2024-11-08_22 31 55](https://github.com/user-attachments/assets/50683507-746d-4005-a5b2-eadd658ca87a)

After adding **doors** to the excluded tags:
![2024-11-08_22 34 53](https://github.com/user-attachments/assets/925e6e7d-5b83-426d-acfa-85e4f32664d0)

**Comment by BlueJayofEvil** [comment]
On a related note, torches and lanterns also have a similar issue:
![2024-11-08_23 45 27](https://github.com/user-attachments/assets/21363e6e-99ef-49e2-9f9e-e3d886b1527e)
![2024-11-08_23 45 36](https://github.com/user-attachments/assets/9bae77db-bb10-4f06-babf-695135e7a4ad)

Adding them to the exclusion list doesn't seem to work in this case.

**Comment by UltimatChamp** [comment]
I've disabled doors and wall (redstone) torches.
I don't think lanterns and normal torches should be disabled.

**Comment by BlueJayofEvil** [comment]
Thank you. 👍 
I checked the new default config and noticed **soul_wall_torch** isn't included on the excluded blocks. Not sure if you want to add that for consistency or not.
Also, I've tried with no success to make it ignore only hanging lanterns. Lanterns have the blockstate property "hanging: true/false" but it's not a separate block like wall torches so excluding the **hanging** tag doesn't work. I agree lanterns should have better snow by default, but the crux of my issue is ones hanging but also have a block underneath get the snow layer applied which I find undesirable. If there is a way to exclude only ones with "hanging: true" please let me know.
Thanks again!

**Comment by UltimatChamp** [comment]
> I checked the new default config and noticed soul_wall_torch isn't included on the excluded blocks. Not sure if you want to add that for consistency or not.

Forgot that they existed.

> Also, I've tried with no success to make it ignore only hanging lanterns.

If a separate id isn't available for hanging lanterns, then I'll have to hardcode my own, like `lantern[hanging=true]`, or something.

**Comment by BlueJayofEvil** [comment]
> If a separate id isn't available for hanging lanterns, then I'll have to hardcode my own, like `lantern[hanging=true]`, or something.
Would it be feasible to have the tags system check for blockstates?
This could add some flexibility going forward and help with anything new added later on.
I'm not sure how difficult that would be so I'm just tossing the idea out there.

**Comment by UltimatChamp** [comment]
> Would it be feasible to have the tags system check for blockstates?

Yes, I've now added it in b7194d9! The new attribute system works for boolean properties, like `block[property=true`(/false)`]`

**Comment by UltimatChamp** [comment]
Thanks for letting me know!
