### ISSUE TITLE
Transparency of snowy leaves

### ISSUE THREAD

**Issue by seriousfreezing** [UltimatChamp/BetterGrassify#39]
### Describe your issue

![2024-11-20_21 25 44](https://github.com/user-attachments/assets/b5962a4c-d46e-4a2b-9765-044d84208e10)

### Mod version

BetterGrassify-1.3.1+fabric.1.21.1

### Launcher

Atlauncher

**Comment by UltimatChamp** [comment]
This is why leaves are disabled by default, in excluded tags.
