### ISSUE TITLE
BetterGrassify does not appear with Sodium [1.21.4]

### ISSUE THREAD

**Issue by TimmyChips** [UltimatChamp/BetterGrassify#42]
### Describe your issue

BetterGrassify works flawlessly without Sodium, but when adding Sodium, the grass does not appear. The new settings inside of Sodium appear under the video settings, but something about Sodium is overwriting the rendering of blocks from BetterGrassify.

Moss Carpet and Snow do extend to other blocks, so that does work. 

### Mod version

1.4.0+fabric.1.21.4

### Launcher

Fabric

### Additional context

Only line related to the mod I can see in latest.log is `[12:44:59] [Render thread/INFO]: Successfully loaded image 'bettergrass:textures/images/bettergrassmode.webp'`, so it does seem to load the texture fine.

**Comment by UltimatChamp** [comment]
I don't think there are any significant changes in the mod in 1.21.4, except for using Fabric's Model Loading API instead of a mixin into vanilla directly (which shouldn't affect Sodium). Sodium's FRAPI's `emitBlockQuads` implementation might be broken. You should report to them instead.

**Comment by UltimatChamp** [comment]
> Only line related to the mod I can see in latest.log is [12:44:59] [Render thread/INFO]: Successfully loaded image 'bettergrass:textures/images/bettergrassmode.webp', so it does seem to load the texture fine.

This is just an [image/preview](https://github.com/UltimatChamp/BetterGrassify/raw/refs/heads/main/src/main/resources/assets/bettergrass/textures/images/bettergrassmode.webp) for the YACL config screen.

**Comment by ImGRUI** [comment]
I think this is related to this bug
![image](https://github.com/user-attachments/assets/b37bfe9d-5b4f-4294-a373-951e377b0a4a)

**Comment by UltimatChamp** [comment]
So, it does seem to be a Sodium bug.

![image](https://github.com/user-attachments/assets/932f89ab-4421-40e4-adf4-ef41cb4960dd)

![image](https://github.com/user-attachments/assets/147ab805-dc7d-40cc-810e-bbc82c500288)

**Comment by TimmyChips** [comment]
> So, it does seem to be a Sodium bug.

Ah, that's super unfortunate to hear. This mod is phenomenal so hopefully the Sodium team manage to get a fix going to fix the block rendering!

**Comment by UltimatChamp** [comment]
Seems to be fixed by https://github.com/CaffeineMC/sodium/commit/a40937b!

**Comment by UltimatChamp** [comment]
Fixed with **Sodium 0.6.6**!
