### ISSUE TITLE
BetterGrassify doesn't work anymore

### ISSUE THREAD

**Issue by Cephalaspis** [UltimatChamp/BetterGrassify#44]
### Describe your issue

Grass sides don't complete, no matter what option I choose. I played a few days ago and it worked fine, I haven't changed or added anything else to any folder or installation so I'm not sure why it suddenly stopped working.
![2024-12-20_01 01 59](https://github.com/user-attachments/assets/28f1275f-1576-497c-8b87-01c855b68e4b)

### Mod version

1.4.1 for Minecraft 1.21.4

### Launcher

The default Minecraft Launcher

**Comment by UltimatChamp** [comment]
Can you upload your `latest.log` file to https://mclo.gs and provide the link here?

**Comment by Cephalaspis** [comment]
Here it is: https://mclo.gs/4KNiMqE

**Comment by UltimatChamp** [comment]
It looks like you have **Sodium** installed. **BetterGrassify** doesn't currently work with **Sodium** on 1.21.4. Wait for **Sodium 0.6.6**, which should fix the issue.

**Comment by UltimatChamp** [comment]
Closing this issue. You can follow #42 for updates instead.
